### ISSUE TITLE
README.md instruction for importing do not work...

### ISSUE THREAD

**Issue by dglaude** [jayniz/unicorn-hat-sim#1]
I have been confused by the explanation on how to import the simulator.
I don't understand the need for "as unicorn".
The demo.py code for unicornhd from @Pimoroni works with this simpler treatment:
```
#import unicornhathd
from unicorn_hat_sim import unicornhathd

```

**Comment by jayniz** [comment]
Yeah, as what you import the unicorn is completely up to you :)
